variable "VPC_CIDR_BLOCK" {}
variable "ENV" {}
variable "COMPONENT" {}
variable "SUBNET_CIDR" {}
variable "AZ" {}
variable "NODE_TYPE" {}
variable "VPC_ID" {}
variable "VPC_CIDR" {}
variable "SUBNET_IDS" {}